FROM localhost/lvp-eigen5:latest

WORKDIR /build

RUN xbps-install -Sy base-devel cmake ninja git perl pkg-config \
    glu-devel MesaLib-devel libX11-devel libXext-devel libXrender-devel \
    libXinerama-devel libXi-devel libXrandr-devel libXcursor-devel \
    gtk+3-devel dbus-devel libcurl-devel \
    gmp-devel mpfr-devel

RUN git clone --depth 1 https://github.com/OrcaSlicer/OrcaSlicer.git /build/OrcaSlicer
WORKDIR /build/OrcaSlicer
RUN git submodule update --init --recursive --jobs 8

# Build OrcaSlicer's bundled dependencies
WORKDIR /build/OrcaSlicer/deps
RUN mkdir build && cd build && \
    cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release && \
    ninja -j1

# Build OrcaSlicer using Eigen5
WORKDIR /build/OrcaSlicer
RUN mkdir build && cd build && \
    cmake .. -G Ninja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_PREFIX_PATH="/build/OrcaSlicer/deps/build/destdir/usr/local;/opt/eigen5" \
      -DEIGEN3_INCLUDE_DIR=/opt/eigen5/include/eigen3 \
      -DCMAKE_INSTALL_PREFIX=/opt/orcaslicer-portable && \
    ninja && \
    ninja install
